-- Create the attendance table
create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  mobile_number text not null
);

-- Enable Row Level Security (RLS)
alter table public.attendance enable row level security;

-- Policy to allow reading attendance (Filtered by mobile_number in the app)
create policy "Enable read access for all users"
on public.attendance for select
using (true);

-- Policy to allow inserting attendance (Used when joining /live session)
create policy "Enable insert access for all users"
on public.attendance for insert
with check (true);
